--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1
-- Dumped by pg_dump version 14.5

-- Started on 2022-12-22 20:11:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 15 (class 2615 OID 26586)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 248 (class 1259 OID 26767)
-- Name: checkbox_casestudy_1_1; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.checkbox_casestudy_1_1 (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    option_1 boolean NOT NULL,
    option_2 boolean DEFAULT false NOT NULL,
    option_3 boolean DEFAULT false NOT NULL
);


ALTER TABLE public.checkbox_casestudy_1_1 OWNER TO supabase_admin;

--
-- TOC entry 249 (class 1259 OID 26773)
-- Name: checkbox_casestudy_1_1_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.checkbox_casestudy_1_1 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.checkbox_casestudy_1_1_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 26774)
-- Name: checkbox_casestudy_1_2; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.checkbox_casestudy_1_2 (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    option_1 boolean NOT NULL,
    option_2 boolean NOT NULL,
    option_3 boolean NOT NULL
);


ALTER TABLE public.checkbox_casestudy_1_2 OWNER TO supabase_admin;

--
-- TOC entry 251 (class 1259 OID 26778)
-- Name: checkbox_casestudy_1_2_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.checkbox_casestudy_1_2 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.checkbox_casestudy_1_2_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2886 (class 0 OID 26767)
-- Dependencies: 248
-- Data for Name: checkbox_casestudy_1_1; Type: TABLE DATA; Schema: public; Owner: supabase_admin
--

COPY public.checkbox_casestudy_1_1 (id, created_at, option_1, option_2, option_3) FROM stdin;
1	2022-10-14 00:42:39.313115+00	t	f	f
\.


--
-- TOC entry 2888 (class 0 OID 26774)
-- Dependencies: 250
-- Data for Name: checkbox_casestudy_1_2; Type: TABLE DATA; Schema: public; Owner: supabase_admin
--

COPY public.checkbox_casestudy_1_2 (id, created_at, option_1, option_2, option_3) FROM stdin;
\.


--
-- TOC entry 2900 (class 0 OID 0)
-- Dependencies: 249
-- Name: checkbox_casestudy_1_1_id_seq; Type: SEQUENCE SET; Schema: public; Owner: supabase_admin
--

SELECT pg_catalog.setval('public.checkbox_casestudy_1_1_id_seq', 3, true);


--
-- TOC entry 2901 (class 0 OID 0)
-- Dependencies: 251
-- Name: checkbox_casestudy_1_2_id_seq; Type: SEQUENCE SET; Schema: public; Owner: supabase_admin
--

SELECT pg_catalog.setval('public.checkbox_casestudy_1_2_id_seq', 26, true);


--
-- TOC entry 2738 (class 2606 OID 26831)
-- Name: checkbox_casestudy_1_1 checkbox_casestudy_1_1_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.checkbox_casestudy_1_1
    ADD CONSTRAINT checkbox_casestudy_1_1_pkey PRIMARY KEY (id);


--
-- TOC entry 2740 (class 2606 OID 26833)
-- Name: checkbox_casestudy_1_2 checkbox_casestudy_1_2_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.checkbox_casestudy_1_2
    ADD CONSTRAINT checkbox_casestudy_1_2_pkey PRIMARY KEY (id);


--
-- TOC entry 2884 (class 3256 OID 26913)
-- Name: checkbox_casestudy_1_1 Enable read access for all users; Type: POLICY; Schema: public; Owner: supabase_admin
--

CREATE POLICY "Enable read access for all users" ON public.checkbox_casestudy_1_1 FOR SELECT USING (true);


--
-- TOC entry 2895 (class 0 OID 0)
-- Dependencies: 15
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- TOC entry 2896 (class 0 OID 0)
-- Dependencies: 248
-- Name: TABLE checkbox_casestudy_1_1; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.checkbox_casestudy_1_1 TO postgres;
GRANT ALL ON TABLE public.checkbox_casestudy_1_1 TO anon;
GRANT ALL ON TABLE public.checkbox_casestudy_1_1 TO authenticated;
GRANT ALL ON TABLE public.checkbox_casestudy_1_1 TO service_role;


--
-- TOC entry 2897 (class 0 OID 0)
-- Dependencies: 249
-- Name: SEQUENCE checkbox_casestudy_1_1_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.checkbox_casestudy_1_1_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.checkbox_casestudy_1_1_id_seq TO anon;
GRANT ALL ON SEQUENCE public.checkbox_casestudy_1_1_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.checkbox_casestudy_1_1_id_seq TO service_role;


--
-- TOC entry 2898 (class 0 OID 0)
-- Dependencies: 250
-- Name: TABLE checkbox_casestudy_1_2; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.checkbox_casestudy_1_2 TO postgres;
GRANT ALL ON TABLE public.checkbox_casestudy_1_2 TO anon;
GRANT ALL ON TABLE public.checkbox_casestudy_1_2 TO authenticated;
GRANT ALL ON TABLE public.checkbox_casestudy_1_2 TO service_role;


--
-- TOC entry 2899 (class 0 OID 0)
-- Dependencies: 251
-- Name: SEQUENCE checkbox_casestudy_1_2_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.checkbox_casestudy_1_2_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.checkbox_casestudy_1_2_id_seq TO anon;
GRANT ALL ON SEQUENCE public.checkbox_casestudy_1_2_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.checkbox_casestudy_1_2_id_seq TO service_role;


--
-- TOC entry 2349 (class 826 OID 26923)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES  TO service_role;


--
-- TOC entry 2342 (class 826 OID 26924)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES  TO service_role;


--
-- TOC entry 2343 (class 826 OID 26925)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS  TO service_role;


--
-- TOC entry 2344 (class 826 OID 26926)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS  TO service_role;


--
-- TOC entry 2345 (class 826 OID 26927)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES  TO service_role;


--
-- TOC entry 2346 (class 826 OID 26928)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES  TO service_role;


-- Completed on 2022-12-22 20:11:58

--
-- PostgreSQL database dump complete
--

